Repository expl0r3rgu1/OOP21-floppy-floppa, pull requests merged in 2022-03, with the labels that each got.

#15 Movable interface to ab class hotfix
  src/main/utilities/Movable.java
Labels: bug

#16 Background feature
  src/main/infinite_map/Background.java
  src/main/infinite_map/ScrollingBackground.java
  src/resources/images/background.png
  src/resources/images/sample_image.png
Labels: mandatory

#23 Removed setter's wrong argument
  src/main/menu/shop/PurchaseStatus.java
Labels: enhancement

#33 Removed useless constructor arguments
  src/main/menu/shop/Shop.java
Labels: enhancement

#27 Infinite map feature
  src/main/infinite_map/Background.java
  src/main/infinite_map/Map.java
  src/main/infinite_map/ScrollingBackground.java
  src/main/infinite_map/TimedFixedObstacleGenerator.java
  src/main/infinite_map/TimedMovingObstacleGenerator.java
  src/main/infinite_map/TimedObstacleGenerator.java
  src/resources/images/background.png
  src/resources/images/sample_image.png
Labels: mandatory

#39 File updater hotfix
  src/main/menu/shop/Shop.java
Labels: mandatory

#43 Missing getters implemented
  src/main/menu/shop/Shop.java
Labels: enhancement, mandatory

#44 Moving obstacle feature
  src/main/obstacles/MovingObstacle.java
Labels: mandatory, milestone

#46 Wrong actionlistener usage hotfix
  src/main/character/Character.java
Labels: bug
