Repository expl0r3rgu1/OOP21-floppy-floppa, pull requests merged in 2022-04, with the labels that each got.

#52 made correct implementetion of FixedObstacle
  src/main/obstacles/FixedObstacle.java
Labels: invalid

#53 Shop gui feature
  src/main/menu/shop/GraphicJButton.java
  src/main/menu/shop/GraphicJLabel.java
  src/main/menu/shop/ShopGUI.java
  src/resources/images/Beach.png
  src/resources/images/Buding.png
  src/resources/images/Capibara.png
  src/resources/images/Classic.png
  src/resources/images/Floppa.png
  src/resources/images/NeonCity.png
  src/resources/images/Quokka.png
  src/resources/images/ShopBackground.png
  src/resources/images/Sogga.png
  src/resources/images/Space.png
  src/resources/images/Woods.png
  src/resources/images/sample_image.png
Labels: mandatory, milestone

#54 Purchase status feature
  src/main/menu/shop/PurchaseStatus.java
Labels: mandatory, milestone

#60 Solved issues #48 and #49
  src/main/obstacles/MovingObstacle.java
Labels: invalid

#59 End of game GUI feature
  src/main/menu/EOGMenuGUI.java
  src/main/utilities/GraphicJButton.java
  src/main/utilities/GraphicJButtonWithObject.java
  src/main/utilities/GraphicJLabel.java
  src/resources/fonts/flips.otf
  src/resources/images/background.png
Labels: mandatory, milestone

#65 Leaderboard feature
  src/main/menu/leaderboard/Leaderboard.java
  src/main/menu/leaderboard/LeaderboardPanel.java
  src/main/menu/leaderboard/Player.java
  src/resources/fonts/fipps.otf
  src/resources/fonts/pixel.TTF
  src/resources/fonts/sample_font.otf
  src/resources/images/background.png
Labels: mandatory, milestone

#71 Obstacle feature
  src/main/obstacles/FixedObstacle.java
  src/main/obstacles/Obstacle.java
Labels: mandatory, milestone

#81 Corrected animate implementation in Obstacle
  src/main/obstacles/FixedObstacle.java
  src/main/obstacles/Obstacle.java
Labels: bug

#82 Updated with correct methods' names
  src/main/menu/EOGMenu.java
Labels: bug

#85 Fixed constructor usage
  src/main/menu/shop/ShopGUI.java
Labels: bug

#91 Added missing mainMenu field in ShopGUI class
  src/main/menu/shop/ShopGUI.java
Labels: enhancement

#92 Added missing mainMenu field in EOGMenuGUI class
  src/main/menu/EOGMenuGUI.java
Labels: enhancement

#103 replaced position with getPosition() in FixedObstacle
  src/main/obstacles/FixedObstacle.java
Labels: bug

#102 Statechanger feature
  src/main/state_changers/StateChanger.java
Labels: mandatory, milestone

#106 Added moving obstacles images for the skins
  src/resources/images/Bingus.png
  src/resources/images/Walter.png
Labels: enhancement

#104 Replaced this.position with getPosition and setPosition
  src/main/obstacles/MovingObstacle.java
Labels: bug, invalid

#110 removed setPosition in FixedObstacle's constructor
  src/main/obstacles/FixedObstacle.java
Labels: invalid

#113 Removed useless redundant font
  src/main/menu/EOGMenuGUI.java
  src/resources/fonts/flips.otf
Labels: enhancement

#101 Malus feature
  src/main/state_changers/BlackStain.java
  src/main/state_changers/BlindBlock.java
  src/main/state_changers/CoinsReducer.java
  src/main/state_changers/Malus.java
  src/main/state_changers/StainPanel.java
  src/resources/images/blackstains.png
  src/resources/images/blindBlock.png
Labels: mandatory, milestone

#109 Added missing instantiation of EOGMenu in EOGMenuGUI Constructor
  src/main/menu/EOGMenu.java
  src/main/menu/EOGMenuGUI.java
Labels: bug

#107 Wrong shop arrays initialization hotfix
  src/main/menu/shop/Shop.java
  src/main/menu/shop/ShopGUI.java
Labels: bug

#108 Booster feature
  src/main/state_changers/Booster.java
  src/main/state_changers/CoinsIncrement.java
  src/main/state_changers/Immortality.java
  src/resources/images/Immortality.png
  src/resources/images/MoneyIncrement.png
Labels: enhancement

#116 Constants feature
  src/main/utilities/Constants.java
Labels: enhancement

#117 Gridbagconstraints simplified subclass enhancement
  src/main/utilities/GBCSimplified.java
Labels: enhancement

#118 Utility methods enhancement
  src/main/utilities/CommonMethods.java
Labels: enhancement

#121 Removed unused import and changed parameter name
  src/main/character/Character.java
Labels: enhancement

#115 Thread.sleep() to Timer in moving obstacle hotfix
  src/main/obstacles/MovingObstacle.java
Labels: bug

#124 Using constants in eog
  src/main/menu/EOGMenuGUI.java
Labels: enhancement

#126 Using constants in booster classes
  src/main/state_changers/Booster.java
  src/main/state_changers/CoinsIncrement.java
  src/main/state_changers/Immortality.java
Labels: enhancement

#123 Using constants in shop
  src/main/menu/shop/Shop.java
  src/main/menu/shop/ShopGUI.java
Labels: enhancement

#128 Fixed collide() and checkCollision() methods
  src/main/character/Character.java
Labels: bug

#130 added png image of fixedObstacle
  src/resources/images/pipe.png
Labels: enhancement

#132 Common methods in eog
  src/main/menu/EOGMenuGUI.java
Labels: enhancement

#133 Using constants in game physics classes
  src/main/character/Character.java
  src/main/utilities/Position.java
Labels: enhancement

#135 Common Methods in GraphicJLabel
  src/main/utilities/GraphicJLabel.java
Labels: enhancement

#139 Infinite map constants enhancement
  src/main/infinite_map/Background.java
  src/main/infinite_map/Map.java
  src/main/infinite_map/ScrollingBackground.java
  src/main/infinite_map/TimedFixedObstacleGenerator.java
  src/main/infinite_map/TimedMovingObstacleGenerator.java
  src/main/infinite_map/TimedObstacleGenerator.java
Labels: enhancement

#146 Using CommonMethods in ScrollingBackground class
  src/main/infinite_map/ScrollingBackground.java
Labels: enhancement

#136 Using GBCSimplified Constructor in Shop
  src/main/menu/shop/Shop.java
  src/main/menu/shop/ShopGUI.java
Labels: enhancement

#137 Using GBCSimplified Constructor in EOGMenuGUI
  src/main/menu/EOGMenuGUI.java
Labels: enhancement

#144 Corrected indentation in Booster class
  src/main/state_changers/Booster.java
Labels: enhancement

#141 Removed scale in paintComponent method of EOGMenuGUI
  src/main/menu/EOGMenuGUI.java
Labels: enhancement

#142 Leaderboard constants enhancement
  src/main/menu/leaderboard/Leaderboard.java
  src/main/menu/leaderboard/LeaderboardPanel.java
Labels: enhancement

#148 Constants hotfix
  src/main/infinite_map/TimedFixedObstacleGenerator.java
  src/main/infinite_map/TimedMovingObstacleGenerator.java
  src/main/utilities/Constants.java
Labels: bug

#152 Removed parenthesis that used to wrap the percentage / 100 operation …
  src/main/utilities/CommonMethods.java
Labels: bug

#155 Added SAVINGS_FILE_START_CONTENT constant
  src/main/utilities/Constants.java
Labels: enhancement

#153 Image background hotfix
  src/main/menu/MenuPanel.java
  src/resources/images/Background.png
Labels: enhancement

#154 Moving obstacle hotfix
  src/main/obstacles/MovingObstacle.java
Labels: invalid

#157 Changed code in animate()
  src/main/character/Character.java
Labels: enhancement

#158 Booster hotfix
  src/main/state_changers/CoinsIncrement.java
  src/main/state_changers/Immortality.java
Labels: invalid

#160 Removed validPosition() in Position
  src/main/utilities/Position.java
Labels: enhancement

#162 Shop hotfix
  src/main/menu/shop/Shop.java
Labels: bug

#163 Javadoc comments for shop feature
  src/main/menu/shop/PurchaseStatus.java
  src/main/menu/shop/Shop.java
  src/main/menu/shop/ShopGUI.java
Labels: enhancement

#164 Javadoc eog feature enhancement
  src/main/menu/EOGMenu.java
  src/main/menu/EOGMenuGUI.java
Labels: enhancement

#172 Added CHANGE_DIRECTION_TIMEOUT constant
  src/main/utilities/Constants.java
Labels: enhancement

#171 changed SIZE to Constants.SCREEN_SIZE
  src/main/obstacles/FixedObstacle.java
Labels: enhancement

#169 Javadoc comments for GraphicJButton and GraphicJLabel classes
  src/main/utilities/GraphicJButton.java
  src/main/utilities/GraphicJButtonWithObject.java
  src/main/utilities/GraphicJLabel.java
Labels: enhancement

#176 Created method to get video resource
  src/main/utilities/CommonMethods.java
Labels: enhancement

#168 Javadoc comments enhancement for priced items
  src/main/utilities/PricedBackground.java
  src/main/utilities/PricedItem.java
  src/main/utilities/PricedSkin.java
Labels: enhancement

#167 Constants malus enhancement
  src/main/state_changers/BlackStain.java
  src/main/state_changers/BlindBlock.java
  src/main/state_changers/CoinsReducer.java
  src/main/state_changers/StainPanel.java
Labels: enhancement

#166 Javadoc comments for booster feature
  src/main/state_changers/Booster.java
  src/main/state_changers/CoinsIncrement.java
  src/main/state_changers/Immortality.java
Labels: enhancement

#165 JavaDocs comments for MovingObstacle class
  src/main/obstacles/MovingObstacle.java
Labels: enhancement

#174 Added missing shop initialization in EOGMenu class
  src/main/menu/EOGMenu.java
Labels: bug

#179 Obstaclefactory hotfix
  src/main/obstacles/FixedObstacle.java
  src/main/obstacles/MovingObstacle.java
  src/main/obstacles/Obstacle.java
  src/main/obstacles/ObstacleFactory.java
  src/main/obstacles/ObstacleFactoryImpl.java
Labels: enhancement

#180 Statechangersfactory hotfix
  src/main/state_changers/Booster.java
  src/main/state_changers/CoinsIncrement.java
  src/main/state_changers/Immortality.java
  src/main/state_changers/Malus.java
  src/main/state_changers/StainPanel.java
  src/main/state_changers/StateChanger.java
  src/main/state_changers/StateChangerFactory.java
  src/main/state_changers/StateChangerFactoryImpl.java
Labels: enhancement

#188 Malus addxposition hotfix
  src/main/state_changers/BlackStain.java
  src/main/state_changers/BlindBlock.java
  src/main/state_changers/CoinsReducer.java
Labels: invalid

#187 changed function showCard
  src/main/menu/MainMenu.java
Labels: enhancement

#185 Eog hotfix
  src/main/menu/EOGMenu.java
Labels: bug

#182 Infinite map hotfix
  src/main/infinite_map/Map.java
  src/main/infinite_map/ScrollingBackground.java
  src/main/infinite_map/TimedFixedObstacleGenerator.java
  src/main/infinite_map/TimedMovingObstacleGenerator.java
  src/main/infinite_map/TimedObstacleGenerator.java
  src/main/utilities/Constants.java
Labels: enhancement

#184 Changed collide(StateChanger) method
  src/main/character/Character.java
Labels: invalid

#189 Moving obstacle hotfix
  src/main/obstacles/MovingObstacle.java
Labels: enhancement

#191 Fileplayer mainmenu hotfix
  src/main/menu/MainMenu.java
Labels: enhancement

#190 Commonmethod malus hotfix
  src/main/state_changers/BlackStain.java
  src/main/state_changers/BlindBlock.java
  src/main/state_changers/CoinsReducer.java
Labels: enhancement

#192 Game engine feature
  src/main/game_engine/Launcher.java
  src/main/game_engine/MainFrame.java
  src/main/game_engine/NicknamePanel.java
  src/main/game_engine/PlayPanel.java
Labels: mandatory, milestone

#194 Changed getVideoResource() to getGifResource()
  src/main/utilities/CommonMethods.java
Labels: enhancement

#198 Jpanel skin feature
  src/main/menu/SkinSelectionPanel.java
Labels: enhancement, milestone

#199 Infinite map hotfix
  src/main/infinite_map/Map.java
  src/main/infinite_map/TimedObstacleGenerator.java
Labels: bug

#197 Added width and height fields to Skin
  src/main/utilities/Skin.java
Labels: enhancement

#201 Game engine feature
  src/main/game_engine/PlayPanel.java
Labels: bug

#203 Constants hotfix
  src/main/utilities/Constants.java
Labels: invalid

#205 Infinite map hotfix
  src/main/infinite_map/Map.java
  src/main/infinite_map/ScrollingBackground.java
  src/main/infinite_map/TimedObstacleGenerator.java
Labels: enhancement

#206 Now using getPixelsFromPercentage instead of inline constants
  src/main/menu/leaderboard/LeaderboardPanel.java
Labels: enhancement

#207 added spawn images for maluses
  src/resources/images/Blackstain_image.png
  src/resources/images/Coins_reducer.png
Labels: enhancement

#208 Fixed collide methods
  src/main/character/Character.java
Labels: bug

#211 Add jpanel mainmenu hotfix
  src/main/menu/MainMenu.java
Labels: enhancement

#214 Priced items hotfix
  src/main/utilities/PricedBackground.java
  src/main/utilities/PricedItem.java
  src/main/utilities/PricedSkin.java
Labels: enhancement

#210 Background music feature
  src/main/game_engine/MainFrame.java
Labels: mandatory, milestone

#215 Added PricedSkin constructor fields where PricedSkin is used
  src/main/menu/shop/Shop.java
Labels: enhancement

#209 moving factor hotfix
  src/main/utilities/Constants.java
Labels: bug, enhancement, invalid

#202 Shop hotfix
  src/main/menu/shop/Shop.java
  src/main/menu/shop/ShopGUI.java
Labels: bug

#213 added use of GameSettings in SkinSelectionPanel
  src/main/menu/SkinSelectionPanel.java
Labels: enhancement

#217 Removed wrong part of a String
  src/main/menu/EOGMenuGUI.java
Labels: invalid

#218 Created clearSavings method
  src/main/menu/shop/Shop.java
Labels: enhancement

#220 Added new constructor in GBCSimplified
  src/main/utilities/GBCSimplified.java
Labels: enhancement

#221 Tutorial feature
  src/main/menu/tutorial/TutorialPanel.java
Labels: mandatory, milestone

#224 Javadoc menu hotfix
  src/main/menu/MainMenu.java
  src/main/menu/MenuPanel.java
Labels: enhancement

#225 Improved size of image resources and gave them a pixel arcade vibe
  src/resources/images/Background.png
  src/resources/images/Beach.png
  src/resources/images/Bingus.png
  src/resources/images/Buding.png
  src/resources/images/Capibara.png
  src/resources/images/Classic.png
  src/resources/images/Floppa.png
  src/resources/images/Immortality.png
  src/resources/images/MoneyIncrement.png
  src/resources/images/NeonCity.png
  src/resources/images/Quokka.png
  src/resources/images/Sogga.png
  src/resources/images/Space.png
  src/resources/images/Walter.png
  src/resources/images/Woods.png
  src/resources/images/blackstains.png
  src/resources/images/pipe.png
Labels: enhancement

#236 Priced items override equals methods
  src/main/utilities/PricedBackground.java
  src/main/utilities/PricedSkin.java
Labels: enhancement

#235 Added override equals method
  src/main/utilities/Movable.java
  src/main/utilities/Position.java
  src/main/utilities/Skin.java
Labels: enhancement

#228 Shop wrong file reading hotfix
  src/main/menu/shop/Shop.java
  src/main/menu/shop/ShopGUI.java
Labels: bug

#231 Javadoc malus enhancement
  src/main/state_changers/BlackStain.java
  src/main/state_changers/BlindBlock.java
  src/main/state_changers/CoinsReducer.java
  src/main/state_changers/Malus.java
  src/main/state_changers/StainPanel.java
  src/main/state_changers/StateChangerFactory.java
  src/main/state_changers/StateChangerFactoryImpl.java
Labels: enhancement

#232 Booster junit ehnancement
  src/junit/TestCoinsIncrement.java
  src/junit/TestImmortality.java
Labels: enhancement

#230 Moving obstacle hotfix
  src/main/obstacles/MovingObstacle.java
Labels: invalid

#229 Update menu enhancement
  src/main/menu/MainMenu.java
  src/main/menu/MenuPanel.java
Labels: enhancement

#223 Used MOVING_FACTOR constant in Character class
  src/main/character/Character.java
Labels: enhancement

#226 Update obstacle enhancement
  src/main/obstacles/FixedObstacle.java
  src/main/obstacles/ObstacleFactory.java
  src/main/obstacles/ObstacleFactoryImpl.java
  src/main/utilities/Constants.java
Labels: enhancement

#253 Update maluses enhancement
  src/main/state_changers/BlackStain.java
  src/main/state_changers/BlindBlock.java
  src/main/state_changers/CoinsReducer.java
Labels: enhancement

#250 Constants enhancement
  src/main/utilities/Constants.java
Labels: enhancement

#249 Common methods enhancement
  src/main/utilities/CommonMethods.java
Labels: enhancement

#252 Fixed collideBorders() method
  src/main/character/Character.java
Labels: bug

#247 Booster images names hotfix
  src/junit/TestCoinsIncrement.java
  src/junit/TestImmortality.java
  src/resources/images/coinsincrement.png
  src/resources/images/immortality.png
Labels: enhancement, invalid

#246 StateChangerFactory hotfix
  src/main/state_changers/StateChangerFactory.java
  src/main/state_changers/StateChangerFactoryImpl.java
Labels: invalid

#245 EOGMenuGUI width height hotfix
  src/main/menu/EOGMenuGUI.java
Labels: bug

#244 Made position private
  src/main/utilities/Movable.java
Labels: invalid

#241 Malus hotfix
  src/main/state_changers/BlackStain.java
  src/main/state_changers/BlindBlock.java
  src/main/state_changers/CoinsReducer.java
  src/main/state_changers/Malus.java
  src/main/state_changers/StainPanel.java
  src/main/state_changers/StateChangerFactory.java
  src/main/state_changers/StateChangerFactoryImpl.java
  src/resources/images/blackstains.png
  src/resources/images/blindBlock.png
  src/resources/images/coinsreducer.png
Labels: enhancement

#242 ShopGUI width height hotfix
  src/main/menu/shop/ShopGUI.java
Labels: bug

#239 Shop junit enhancement
  src/junit/TestShop.java
  src/main/menu/shop/Shop.java
Labels: enhancement

#255 Added serial ID to GBCSimplified class
  src/main/utilities/GBCSimplified.java
Labels: enhancement

#240 Mainmenu hotfix
  src/main/menu/MainMenu.java
  src/main/menu/MenuPanel.java
Labels: enhancement

#257 Shop hotfix
  src/main/menu/shop/Shop.java
  src/main/menu/shop/ShopGUI.java
Labels: bug

#258 Selectionpanel hotfix
  src/main/menu/SelectionPanel.java
  src/main/utilities/GameSettings.java
Labels: enhancement

#256 Booster width height hotfix
  src/main/state_changers/CoinsIncrement.java
  src/main/state_changers/Immortality.java
Labels: bug

#267 Score management feature
  src/main/game_engine/PlayPanel.java
Labels: mandatory, milestone

#268 Game engine hotfix
  src/main/game_engine/NicknamePanel.java
  src/main/game_engine/PlayPanel.java
Labels: enhancement

#270 State changer spawner feature
  src/main/infinite_map/Map.java
  src/main/infinite_map/TimedEntityGenerator.java
  src/main/infinite_map/TimedObstacleGenerator.java
  src/main/infinite_map/TimedStateChangerGenerator.java
Labels: enhancement, mandatory

#263 Changed collide methods for malus and booster
  src/main/character/Character.java
Labels: enhancement

#264 Used common constants and methods in tutorial
  src/main/menu/tutorial/TutorialPanel.java
Labels: enhancement

#269 Game engine feature
  src/main/game_engine/MainFrame.java
  src/main/game_engine/NicknamePanel.java
  src/main/game_engine/PlayPanel.java
Labels: bug, enhancement, mandatory

#272 Infinite map hotfix
  src/main/infinite_map/Map.java
  src/main/infinite_map/TimedEntityGenerator.java
  src/main/infinite_map/TimedObstacleGenerator.java
  src/main/infinite_map/TimedStateChangerGenerator.java
Labels: bug, enhancement, mandatory

#276 Leaderboard hotfix
  src/main/menu/leaderboard/Leaderboard.java
  src/main/menu/leaderboard/LeaderboardPanel.java
Labels: bug, invalid

#284 Leaderboard hotfix
  src/main/menu/leaderboard/Leaderboard.java
Labels: bug, mandatory

#280 added constant SPACE_BETWEEN_PIPES
  src/main/utilities/Constants.java
Labels: enhancement

#279 Update malus enhancement
  src/main/state_changers/BlackStain.java
  src/main/state_changers/BlindBlock.java
  src/main/state_changers/CoinsReducer.java
Labels: enhancement

#283 Boosters hotfix
  src/main/state_changers/Booster.java
  src/main/state_changers/CoinsIncrement.java
  src/main/state_changers/Immortality.java
  src/resources/images/coinsincrement.png
Labels: bug, documentation, enhancement

#282 Removed unused imports
  src/main/obstacles/MovingObstacle.java
Labels: enhancement

#281 Eog hotfix
  src/main/menu/EOGMenu.java
  src/main/menu/EOGMenuGUI.java
Labels: bug, documentation, enhancement

#278 Used constants and common methods in game physics classes
  src/main/character/Character.java
Labels: enhancement

#286 Added javadoc comments in initial tutorial class
  src/main/menu/tutorial/TutorialPanel.java
Labels: documentation, enhancement

#285 Update menu enhancement
  src/main/menu/MainMenu.java
  src/main/menu/MenuPanel.java
  src/main/menu/SelectionPanel.java
  src/main/utilities/GraphicJButton.java
Labels: enhancement

#289 Skin dimension constant hotfix
  src/main/menu/SelectionPanel.java
  src/main/utilities/Constants.java
Labels: enhancement

#287 Added documentation in game physics classes
  src/main/character/Character.java
  src/main/utilities/Movable.java
  src/main/utilities/Position.java
  src/main/utilities/Skin.java
Labels: documentation, enhancement

#290 Skins images hotfix
  src/resources/images/Bingus.png
  src/resources/images/Buding.png
  src/resources/images/Capibara.png
  src/resources/images/Floppa.png
  src/resources/images/Quokka.png
  src/resources/images/Sogga.png
  src/resources/images/Walter.png
Labels: enhancement, invalid

#295 Infinite map hotfix
  src/main/infinite_map/Background.java
  src/main/infinite_map/Map.java
Labels: enhancement

#294 Game engine feature
  src/main/game_engine/NicknamePanel.java
  src/main/game_engine/PlayPanel.java
Labels: mandatory, milestone

#296 Leaderboard hotfix
  src/main/menu/leaderboard/Leaderboard.java
  src/main/menu/leaderboard/LeaderboardPanel.java
Labels: bug, enhancement

#293 Changed the string when using a font
  src/main/menu/tutorial/TutorialPanel.java
Labels: bug

#291 Made JUnit tests for common methods
  src/junit/TestCommonMethods.java
Labels: enhancement

#297 Common methods hotfix
  src/main/utilities/CommonMethods.java
Labels: bug, enhancement

#298 Constants enhancement
  src/main/utilities/Constants.java
Labels: enhancement

#299 Fixed Map class constructor
  src/main/infinite_map/Map.java
Labels: bug

#310 Boosters hotfix
  src/main/state_changers/Booster.java
  src/main/state_changers/CoinsIncrement.java
  src/main/state_changers/Immortality.java
Labels: bug
